import { GetServerSideProps } from 'next'
import Head from 'next/head'
import Homepage from 'src/components/homepage'
import Keys from 'src/models/keys'
import UserModel from 'src/models/user'
import { Container } from 'src/styles/styled'
import connectDB from 'src/utils/connectDb'

interface HomeProps{
  allUsers:{ email:string; password:string; _id:string; _v:number; token:string }[];
  allKeys:{ key:string; _id:string; _v:number }[];
}

export default function Home({ allUsers,allKeys }:HomeProps) {

  return (
    <Container>
      <Head>
        <title>SSS</title>
        <meta name="description" content="Generated by soft softwares solution" />
        <link rel="icon" href="/default.png" />
      </Head>
      <Homepage allUsers={ allUsers } allKeys={ allKeys } />
    </Container>
  )
}

export const getServerSideProps:GetServerSideProps = async()=>{
    
  try{
      console.log("CONNECTING TO DB");
      await connectDB();
      console.log("CONNECTED TO DB");

      console.log("FETCHING USER DOCUMENT");
      const userResult = await UserModel.find().sort({ _id:-1 });
      console.log("FETCHED USER DOCUMENT");

      console.log("FETCHING KEY DOCUMENT");
      const keyResult = await Keys.find().sort({ _id:-1 });
      console.log("FETCHED KEY DOCUMENT");

      return {
          props:{
              allUsers:JSON.parse(JSON.stringify(userResult)),
              allKeys:JSON.parse(JSON.stringify(keyResult))
          }
      }

  }catch(error:any){

      return{
          notFound:true
      }

  }
}

// <div className={styles.container}>
// <Head>
//   <title>SSS</title>
//   <meta name="description" content="Generated by soft softwares solution" />
//   <link rel="icon" href="/default.png" />
// </Head>

// <main className={styles.main}>
//   <h1 className={styles.title}>
//     Welcome to <a href="https://nextjs.org">Next.js!</a>
//   </h1>

//   <p className={styles.description}>
//     Get started by editing{' '}
//     <code className={styles.code}>pages/index.tsx</code>
//   </p>

//   <div className={styles.grid}>
//     <a href="https://nextjs.org/docs" className={styles.card}>
//       <h2>Documentation &rarr;</h2>
//       <p>Find in-depth information about Next.js features and API.</p>
//     </a>

//     <a href="https://nextjs.org/learn" className={styles.card}>
//       <h2>Learn &rarr;</h2>
//       <p>Learn about Next.js in an interactive course with quizzes!</p>
//     </a>

//     <a
//       href="https://github.com/vercel/next.js/tree/canary/examples"
//       className={styles.card}
//     >
//       <h2>Examples &rarr;</h2>
//       <p>Discover and deploy boilerplate example Next.js projects.</p>
//     </a>

//     <a
//       href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
//       target="_blank"
//       rel="noopener noreferrer"
//       className={styles.card}
//     >
//       <h2>Deploy &rarr;</h2>
//       <p>
//         Instantly deploy your Next.js site to a public URL with Vercel.
//       </p>
//     </a>
//   </div>
// </main>

// <footer className={styles.footer}>
//   <a
//     href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
//     target="_blank"
//     rel="noopener noreferrer"
//   >
//     Powered by{' '}
//     <span className={styles.logo}>
//       <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
//     </span>
//   </a>
// </footer>
// </div>